#!/bin/sh
# Init script for qmail-send
# Copied from LWQ

SERVICE=send
. /var/qmail/bin/qmail-config-system && \
exec env - PATH="${PATH}" \
	QMAILREMOTE="${QMAILREMOTE}" \
	qmail-start "$(grep -v '^#' /var/qmail/control/defaultdelivery)"
