#!/bin/bash
# Gentoo Startup script for qmail's POP3 daemon (logging)

SERVICE=pop3s
. /var/qmail/bin/qmail-config-system && \
eval exec /usr/bin/setuidgid qmaill /usr/bin/multilog ${LOG_OPTS} ${LOG_DEST}
